//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lineee.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LineNotify1Entities : DbContext
    {
        public LineNotify1Entities()
            : base("name=LineNotify1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Details> Details { get; set; }
        public virtual DbSet<Doctor> Doctor { get; set; }
        public virtual DbSet<Exam> Exam { get; set; }
        public virtual DbSet<ExaOrderDetails> ExaOrderDetails { get; set; }
        public virtual DbSet<ExaOrders> ExaOrders { get; set; }
        public virtual DbSet<Patient> Patient { get; set; }
        public virtual DbSet<Report> Report { get; set; }
    }
}
